config/routes.rb
Hello::Application.routes.draw do
  resources :posts

  get "home/index"

  get "home/contact"

  root :to => 'home#index'

end

app/models/counter.rb
class Counter < ActiveRecord::Base
  attr_accessible :count
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @counter = Counter.first
    Counter.increment_counter(:count, @counter.id)
    @counter.reload
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("updated_at DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/contact.html.erb
<h1>連絡先</h1>
<p>メールアドレスは <a href="mailto:kouji.takao+heroku2@gmail.com">kouji.takao+heroku2@gmail.com</a> です。</p>

app/views/home/index.html.erb
<h1>高尾のホームページ</h1>
<p>ようこそ、高尾のホームページへいらっしゃいました。</p>
<p>あなたは <%= @counter.count %> 番目の訪問者です。</p>
<p>現在の時刻は <%= Time.zone.now.strftime("%Y年%m月%d日 %H時%M分%S秒") %> です。</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<hr />

<h3>サイトマップ</h3>
<ul>
  <li><%= link_to("トップ", home_index_path) %></li>
  <li><%= link_to("ブログ", posts_path) %></li>
  <li><%= link_to("連絡先", home_contact_path) %></li>
</ul>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, "本文" %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>記事の編集</h1>

<%= render 'form' %>

<%= link_to 'ブログ', posts_path %>

app/views/posts/index.html.erb
<h1>ブログ</h1>

<p style="text-align: right;">
  <%= link_to('記事を書く', new_post_path) %>
</p>

<% @posts.each do |post| %>
<hr />
<h2><%= post.title %></h2>
<p style="text-align: right;">
  <%= post.updated_at.strftime("%Y年%m月%d日 %H時%M分") %>
</p>

<pre><%= post.body %></pre>

<p style="text-align: right;">
  <%= link_to('編集', edit_post_path(post)) %>
  <%= link_to('削除', post, method: :delete, data: { confirm: '本当に削除しますか？' }) %>
</p>

<% end %>

app/views/posts/new.html.erb
<h1>記事を書く</h1>

<%= render 'form' %>

<%= link_to('ブログ', posts_path) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>記事の表示</h1>

<hr />

<h2><%= @post.title %></h2>
<p style="text-align: right;">
  <%= @post.updated_at.strftime("%Y年%m月%d日 %H時%M分") %>
</p>

<pre><%= @post.body %></pre>

<%= link_to '編集', edit_post_path(@post) %> |
<%= link_to 'ブログ', posts_path %>